# Generated by Django 2.0 on 2020-04-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(help_text='Область деятельности', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(help_text='Логин', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Имя', max_length=25)),
                ('lastname', models.CharField(help_text='Фамилия', max_length=50)),
                ('age', models.SmallIntegerField(help_text='Возраст')),
                ('email', models.EmailField(help_text='e-mail', max_length=254)),
                ('social', models.CharField(help_text='Профиль Facebook/Instagram', max_length=100)),
                ('activity', models.ForeignKey(help_text='Выбор деятельности', on_delete=django.db.models.deletion.PROTECT, to='userprofile.Activity')),
            ],
        ),
    ]
