# Generated by Django 2.0 on 2020-04-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Наименование', max_length=255)),
                ('code', models.CharField(help_text='Код товара', max_length=10)),
                ('cost', models.IntegerField()),
            ],
        ),
    ]
