# Generated by Django 2.0 on 2020-04-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(help_text='Область деятельности', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='cost',
            field=models.IntegerField(help_text='Стоимость'),
        ),
    ]
