# Generated by Django 2.0 on 2020-04-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200428_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='e-mail', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social',
            field=models.CharField(blank=True, help_text='Профиль Facebook/Instagram', max_length=100),
        ),
    ]
