# Generated by Django 2.0 on 2020-04-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_auto_20200428_2059'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
