# Generated by Django 2.0 on 2020-04-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_delete_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='login',
            field=models.CharField(max_length=75, primary_key=True, serialize=False, unique=True),
        ),
    ]
