# Generated by Django 2.0 on 2020-05-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.ForeignKey(help_text='Выбор деятельности', null=True, on_delete=django.db.models.deletion.PROTECT, to='userprofile.Activity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social',
            field=models.CharField(blank=True, help_text='Профиль Facebook/Instagram', max_length=100, null=True),
        ),
    ]
