# Generated by Django 2.0 on 2020-05-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20200504_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='descr',
            field=models.CharField(default='', help_text='Описание', max_length=255),
        ),
    ]
