# Generated by Django 2.0 on 2020-05-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_shop_descr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='id',
        ),
        migrations.AlterField(
            model_name='shop',
            name='code',
            field=models.CharField(help_text='Код товара', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
